name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    env:
      REPO_IMAGE_NAME: mvntmct

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Quick debug (masked)
        run: |
          echo "GITHUB_REPOSITORY=$GITHUB_REPOSITORY"
          if [ -n "${{ secrets.DOCKERHUB_USERNAME }}" ]; then
            echo "DOCKERHUB_USERNAME is set"
          else
            echo "DOCKERHUB_USERNAME is NOT set"
          fi
          if [ -n "${{ secrets.DOCKERHUB_TOKEN }}" ]; then
            echo "DOCKERHUB_TOKEN is set"
          else
            echo "DOCKERHUB_TOKEN is NOT set"
          fi

      - name: Compute IMAGE_NAME (safe fallback) and expose it
        id: compute_image
        run: |
          if [ -n "${{ secrets.DOCKERHUB_USERNAME }}" ]; then
            # explicit docker.io prefix optional; we keep simple username/repo:tag
            IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPO_IMAGE_NAME }}:latest"
          else
            # fallback to owner/repo:latest (github_owner/repo)
            IMAGE_NAME="${GITHUB_REPOSITORY}:latest"
          fi
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
          # print the computed value so you can confirm in the log (value is safe: secrets masked)
          echo "Computed IMAGE_NAME='$IMAGE_NAME'"

      - name: Show final tag used (verify)
        run: |
          echo "Final tag to be used: $IMAGE_NAME"
        shell: bash

      - name: Login to Docker Hub (only on push and when secrets exist)
        if: >
          github.event_name == 'push' &&
          secrets.DOCKERHUB_USERNAME != '' &&
          secrets.DOCKERHUB_TOKEN != ''
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image (only on push)
        if: github.event_name == 'push'
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}
          # platforms: linux/amd64,linux/arm64

      - name: Deploy on remote server via SSH (only on push)
        if: github.event_name == 'push'
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT || '22' }}
          timeout: 120
          script: |
            set -e

            # Optional: login on remote host if DockerHub secrets are available
            if [ -n "${{ secrets.DOCKERHUB_USERNAME }}" ] && [ -n "${{ secrets.DOCKERHUB_TOKEN }}" ]; then
              echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin || true
            fi

            # Use the same IMAGE_NAME computed in the workflow
            docker pull ${{ env.IMAGE_NAME }} || true

            if [ "$(docker ps -q -f name=myapp)" ]; then
              docker stop myapp || true
              docker rm myapp || true
            fi

            if docker images -q ${{ env.IMAGE_NAME }} > /dev/null 2>&1; then
              docker rmi ${{ env.IMAGE_NAME }} || true
            fi

            docker run -d --restart unless-stopped -p 8082:8080 --name myapp ${{ env.IMAGE_NAME }}
