name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Build Docker Image
      - name: Build Docker Image
        run: docker build -t mvntmct .

      # Step 4: Run Docker Container
      - name: Run Docker Container
        run: docker run -d -p 8082:8080 mvntmct
